version: "3.8"
services:
  api_lottery:
    image: carlosdiazz08/api_lottery:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    # Otras configuraciones de contenedor
    networks:
      dhcp-relay-net:
        ipv4_address: '172.31.0.10'

  cron_api:
    image: carlosdiazz08/cron_api:latest
    restart: always
    depends_on:
      - api_lottery
    environment:
      - URL_API=http://api_lottery:${PORT}/graphql
      - BUSCAR_SORTEO=true
      - BUSCAR_PREMIO=false
    networks:
      dhcp-relay-net:
        ipv4_address: '172.31.0.11'

networks:
  dhcp-relay-net:
    external: true