version: '3'
services:
  api_lottery:
    image: carlosdiazz08/api_lottery:1.0.0
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    # Otras configuraciones de contenedor

  cron_api:
    image: carlosdiazz08/cron_api:1.0.1
    restart: always
    depends_on:
      - api_lottery
    environment:
      - URL_API=http://api_lottery:${PORT}/graphql
    # Otras configuraciones de contenedor

networks:
  my_network:
    external: true